name: wine_quality
on:
  push:
    branches:
      - develop
      - experiments
  pull_request:
    branches:
      - develop
      - experiments

permissions:
  pull-requests: write
  contents: read

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: alenine74/wine
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml
          cml --version

      - name: Run train.py
        run: |
          python train.py

      - name: Show metrics
        run: |
          echo "MODEL"
          cat metrics.txt

      - name: Create markdown doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model metrics ##" > report.md
          cat metrics.txt >> report.md
          echo "## Data vis##" >> report.md
          cml publish feature_importance.png --md >> report.md
          cml publish residuals.png --md >> report.md
          cml comment create report.md