name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py
          echo "MODEL METRICS"
          cat metrics.txt
