name: wine_quality

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml
          # Verify installation
          cml --version

      - name: Run train.py
        run: |
          python train.py

      - name: Show metrics
        run: |
          echo "MODEL"
          cat metrics.txt

      - name: Create markdown doc
        run: |
          echo "## Model metrics ##" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data vis##" >> report.md
          
          cml publish feature_importance.png --md >> report.md
          cml publish residuals.png --md >> report.md
          cml comment create report.md